project:
  type: website

website:
  title: "Classement OFCN 2024"
  navbar:
    left:
      - href: index.qmd
        text: Classement OFCN 2024
      - href: methodo.qmd
        text: Méthodologie

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

