---
title: "Classement OFCN 2024"
---


```{r, include=FALSE}
library(knitr)
library(tidyverse) 
library(showtext) 
library(ofce)
library(ggpubr)
library(kableExtra)
library(gt)


opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.pos="H", 
  out.extra="",
  dev="ragg_png",
  fig.showtext=TRUE,
  cache=FALSE)

showtext_opts(dpi=200)
showtext_auto()
load("classements2023.rda")
```

La méthodologie est exposée ici :
[Méthodologie](methodo.qmd)

## Classement par score (1)

Classement réalisé avec la pondération suivante :

 - 0.5 x PIB ;
 - 0.2 x Chomage ;
 - 0.2 x Solde;
 - 0.1 x IPCH.

```{r}

gt_scores <- Classement_scores|> 
  rowwise() |> 
  mutate(score_total = (PIB+IPCH+Chomage+`Solde public`),
         score_pondéré = (0.5*PIB+0.2*Chomage+0.2*`Solde public`+0.1*IPCH))|> 
  select(institut,score_total,score_pondéré) |> 
  gt() |> 
  opt_interactive(
    use_pagination = FALSE,
    use_pagination_info = FALSE
  ) %>% 
  tab_style(
    locations = cells_body(columns = institut),
    style = cell_text(weight = "bold")
  ) %>% 
  data_color(
    columns = score_total,
    rows = score_total < sort(score_total)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns = score_pondéré,
    rows = score_pondéré < sort(score_pondéré)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) |> 
tab_options(
  table.font.size = 18) |> 
  fmt_number(decimals= 1)

gt_scores

```

## Classement par score (2)

Classement réalisé avec la pondération suivante :

 - 0.5 x PIB ;
 - Autres variables : 0.167
 
```{r}
gt_scores2 <- Classement_scores|> 
  rowwise() |> 
  mutate(score_total = (PIB+IPCH+Chomage+`Solde public`),
         score_pondéré = (0.5*PIB+0.167*Chomage+0.167*`Solde public`+0.167*IPCH))|> 
  select(institut,score_total,score_pondéré) |> 
  gt() |> 
  opt_interactive(
    use_pagination = FALSE,
    use_pagination_info = FALSE
  ) %>% 
  tab_style(
    locations = cells_body(columns = institut),
    style = cell_text(weight = "bold")
  ) %>% 
  data_color(
    columns = score_total,
    rows = score_total < sort(score_total)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns = score_pondéré,
    rows = score_pondéré < sort(score_pondéré)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) |> 
tab_options(
  table.font.size = 18) |> 
  fmt_number(decimals= 1)

gt_scores2
```


## Classement sans score

Pour rappel : le classement sans calcul de scores (la colonne "total" est la moyenne des classements par variable).

```{r}

gt_2023_old <- Classement_2023 |> 
  gt() |> 
  opt_interactive(
    use_pagination = FALSE,
    use_pagination_info = FALSE
  ) %>% 
  tab_style(
    locations = cells_body(columns = institut),
    style = cell_text(weight = "bold")
  ) %>% 
  data_color(
    columns = PIB,
    rows = PIB < sort(PIB)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns = IPCH,
    rows = IPCH < sort(IPCH)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns = Chomage,
    rows = Chomage < sort(Chomage)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns = `Solde public`,
    rows = `Solde public` < sort(`Solde public`)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) %>% 
  data_color(
    columns =  total,
    rows = total < sort(total)[4],
    method = "factor",
    palette = c("gold", "grey", "brown" )) |> 
tab_options(
  table.font.size = 18) |> 
  as_raw_html()

gt_2023_old

```