---
title: "Méthodologie"
format: html
---

## Calcul des scores

Pour chaque institut $i$ et variable $k$ on calcule un score :

$$score_{i,k}= \frac{|[|\varepsilon_{i,k}|-min(|\varepsilon_{k}|)]|}{\sigma_{|\varepsilon_k|}}$$ Avec $\varepsilon$ l'erreur de prévision pour la variable $k$.

Autrement dit, il s'agit d'une sorte de *z-score* calculé à partir de la plus petite erreur de prévision (en valeur absolue) parmi les participants, plutôt que l'erreur de prévision moyenne.

  - **Rappel** : dans les cas où aucune prévision n'a été fournie pour une variable, on impute la plus grande erreur de prévision parmi les participants. 

On calcule un score total :

- Soit comme somme des scores par variables ;
- Soit comme somme **pondérée** des scores.

-  Pour l'instant la pondération retenue : 
  - 0.5 x PIB ;
  - 0.2 x Chomage ;
  - 0.2 x Solde;
  - 0.1 x IPCH.
  
Dernière remarque : dans quelques cas, les participants ont renseigné des valeurs (IPCH, Chômage) en moyenne annuelle, alors que pour l'OFCN 2022, les valeurs **en fin d'année** avaient été demandées. Dans ces cas-là, les $\varepsilon$ ont bien été calculés en prenant en compte s'il s'agit d'une prévision de moyenne annuelle ou de fin d'année.
